spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create
        format_sql: true
    defer-datasource-initialization: false
  datasource:
    url: jdbc:mysql://localhost:3306/book_manager
    username: root
    password: qqqq1111
